version: '3'
services:
  nginx:
    image: nginx
    container_name: web-server
    working_dir: /app
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php-fpm1:
    image: bitnami/php-fpm
    container_name: "backend1"
    working_dir: /app
    environment:
      - BACKEND_NAME=BACKEND_1
    volumes:
      - ./containers/php-fpm/env.conf:/opt/bitnami/php/etc/environment.conf
      - ./:/app
  php-fpm2:
    image: bitnami/php-fpm
    container_name: "backend2"
    working_dir: /app
    environment:
      - BACKEND_NAME=BACKEND_2
    volumes:
      - ./containers/php-fpm/env.conf:/opt/bitnami/php/etc/environment.conf
      - ./:/app